spring:
  datasource:
    url: jdbc:mysql://localhost:3307/diplomaServer
    username: sacha
    password: warface567
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
        hibernate:
            format_sql: true
    database: mysql