insert into _events
values
(0,
"Test1",
"https://images.unsplash.com/photo-1489549132488-d00b7eee80f1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8N3x8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60",
20,
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tristique porttitor porttitor. Etiam molestie  ut massa eget aliquet. Sed tortor velit, luctus semp er mi elementum, consequat scelerisque massa. Nam eu lorem et erat aliquet sagittis quis eu lorem. Quisque dapibus eleifend ullamcorper. Morbi ultricies massa vel ligula dictum, in finibus dui eleifend. Ut eu eros mi. Duis vitae luctus lorem, in dictum libero. Aliquam honcus scelerisque lacus. Nunc a mi sed magna semper egestas eu a massa. Sed commod o metus sed vehicula pharetra.",
230.32,
324.43,
"2015-02-15 10:30:00"
),
(1,
 "Test2",
 "https://images.unsplash.com/photo-1603788988770-92e7a1b2bea5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTF8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
 123,
 "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tristique porttitor porttitor. Etiam molestie  ut massa eget aliquet. Sed tortor velit, luctus semp er mi elementum, consequat scelerisque massa. Nam eu lorem et erat aliquet sagittis quis eu lorem. Quisque dapibus eleifend ullamcorper. Morbi ultricies massa vel ligula dictum, in finibus dui eleifend. Ut eu eros mi. Duis vitae luctus lorem, in dictum libero. Aliquam honcus scelerisque lacus. Nunc a mi sed magna semper egestas eu a massa. Sed commod o metus sed vehicula pharetra.",
 230.32,
 324.43,
 "2015-02-15 10:30:00"),
 (2,
  "Test3",
  "https://images.unsplash.com/photo-1580740132087-761c25cacbf6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTd8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
  234,
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tristique porttitor porttitor. Etiam molestie  ut massa eget aliquet. Sed tortor velit, luctus semp er mi elementum, consequat scelerisque massa. Nam eu lorem et erat aliquet sagittis quis eu lorem. Quisque dapibus eleifend ullamcorper. Morbi ultricies massa vel ligula dictum, in finibus dui eleifend. Ut eu eros mi. Duis vitae luctus lorem, in dictum libero. Aliquam honcus scelerisque lacus. Nunc a mi sed magna semper egestas eu a massa. Sed commod o metus sed vehicula pharetra.",
  230.32,
  324.43,
  "2015-02-15 10:30:00");